/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AmortizationData, AmortizationRow, LoanFormData, NumericInputTypeEnum } from "./data/models";
import { TabItem } from "./components/tabs-controller/tabs-controller";
export { AmortizationData, AmortizationRow, LoanFormData, NumericInputTypeEnum } from "./data/models";
export { TabItem } from "./components/tabs-controller/tabs-controller";
export namespace Components {
    interface AmortizationEntry {
    }
    interface AmortizationList {
        /**
          * @default []
         */
        "entries": AmortizationData[];
    }
    interface AmortizationSchedule {
        /**
          * @default []
         */
        "schedule": AmortizationRow[];
    }
    interface AmortizationScheduleBase {
        /**
          * @default []
         */
        "amortizationEntries": AmortizationData[];
        "loanData": LoanFormData;
    }
    interface AmortizationScheduleWithAdditional {
        /**
          * @default []
         */
        "amortizationEntries": AmortizationData[];
        "loanData": LoanFormData;
    }
    interface AmortizationScheduleWithoutAdditional {
        "loanData": LoanFormData;
    }
    interface BalanceGraph {
        /**
          * @default []
         */
        "schedule": AmortizationRow[];
    }
    interface BarChart {
        /**
          * @default []
         */
        "schedule": AmortizationRow[];
    }
    interface CumulativePaymentGraph {
        /**
          * @default []
         */
        "schedule": AmortizationRow[];
    }
    interface DateInput {
        /**
          * @default 'date-input'
         */
        "inputId": string;
        /**
          * @default ''
         */
        "max": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface ExportJsonController {
    }
    interface KeyMetricsDashboard {
        "loanData": LoanFormData;
        /**
          * @default []
         */
        "schedule": AmortizationRow[];
    }
    interface LoanAmortizationCalculator {
    }
    interface LoanCalculator {
        "getFormData": () => Promise<LoanFormData>;
        /**
          * @default false
         */
        "hideAdditionalPrincipal"?: boolean;
        "initialFormData"?: LoanFormData;
    }
    interface LoanCalculatorApp {
    }
    interface LoanCalculatorMain {
    }
    interface LoanDetails {
        "loanData": LoanFormData;
    }
    interface LoanReport {
        "loanDataDictionary": { [key: string]: LoanFormData };
    }
    interface LoanSummary {
        "loanData": LoanFormData;
    }
    interface NumberInput {
        /**
          * @default null
         */
        "max": number;
        /**
          * @default 0
         */
        "min": number;
        /**
          * @default 2
         */
        "numberOfDecimalsAllowed": number;
        /**
          * @default NumericInputTypeEnum.Integer
         */
        "numericInputType": NumericInputTypeEnum;
        /**
          * @default ''
         */
        "propertyName": string;
        /**
          * @default true
         */
        "required": boolean;
        "setFocus": () => Promise<void>;
        "validateInput": () => Promise<boolean>;
        /**
          * @default null
         */
        "value": number;
    }
    interface PayoffProgress {
        /**
          * @default []
         */
        "amortizationEntries": AmortizationData[];
        "currentDate"?: string;
        "loanData": LoanFormData;
    }
    interface PieChart {
        /**
          * @default []
         */
        "schedule": AmortizationRow[];
    }
    interface PopupModal {
        /**
          * @default false
         */
        "isOpen": boolean;
        "modalTitle": string;
    }
    interface SavingsComparisonGraph {
        /**
          * @default []
         */
        "amortizationEntries": AmortizationData[];
        "loanData": LoanFormData;
    }
    interface ScheduleSummary {
        /**
          * @default []
         */
        "schedule": AmortizationRow[];
    }
    interface ScheduleView {
        /**
          * @default []
         */
        "schedule": AmortizationRow[];
    }
    interface TabsController {
        /**
          * @default 0
         */
        "defaultActiveIndex"?: number;
        /**
          * @default []
         */
        "tabs": TabItem[];
    }
    interface TextInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default null
         */
        "maxLength": number;
        /**
          * @default ''
         */
        "propertyName": string;
        /**
          * @default true
         */
        "required": boolean;
        "setFocus": () => Promise<void>;
        "validateInput": () => Promise<boolean>;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface AmortizationEntryCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAmortizationEntryElement;
}
export interface AmortizationListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAmortizationListElement;
}
export interface BarChartCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBarChartElement;
}
export interface DateInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDateInputElement;
}
export interface LoanCalculatorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLoanCalculatorElement;
}
export interface LoanSummaryCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLoanSummaryElement;
}
export interface NumberInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNumberInputElement;
}
export interface PopupModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPopupModalElement;
}
export interface ScheduleViewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScheduleViewElement;
}
export interface TabsControllerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTabsControllerElement;
}
export interface TextInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTextInputElement;
}
declare global {
    interface HTMLAmortizationEntryElementEventMap {
        "addEntry": AmortizationData;
    }
    interface HTMLAmortizationEntryElement extends Components.AmortizationEntry, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAmortizationEntryElementEventMap>(type: K, listener: (this: HTMLAmortizationEntryElement, ev: AmortizationEntryCustomEvent<HTMLAmortizationEntryElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAmortizationEntryElementEventMap>(type: K, listener: (this: HTMLAmortizationEntryElement, ev: AmortizationEntryCustomEvent<HTMLAmortizationEntryElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAmortizationEntryElement: {
        prototype: HTMLAmortizationEntryElement;
        new (): HTMLAmortizationEntryElement;
    };
    interface HTMLAmortizationListElementEventMap {
        "deleteEntry": string;
    }
    interface HTMLAmortizationListElement extends Components.AmortizationList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAmortizationListElementEventMap>(type: K, listener: (this: HTMLAmortizationListElement, ev: AmortizationListCustomEvent<HTMLAmortizationListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAmortizationListElementEventMap>(type: K, listener: (this: HTMLAmortizationListElement, ev: AmortizationListCustomEvent<HTMLAmortizationListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAmortizationListElement: {
        prototype: HTMLAmortizationListElement;
        new (): HTMLAmortizationListElement;
    };
    interface HTMLAmortizationScheduleElement extends Components.AmortizationSchedule, HTMLStencilElement {
    }
    var HTMLAmortizationScheduleElement: {
        prototype: HTMLAmortizationScheduleElement;
        new (): HTMLAmortizationScheduleElement;
    };
    interface HTMLAmortizationScheduleBaseElement extends Components.AmortizationScheduleBase, HTMLStencilElement {
    }
    var HTMLAmortizationScheduleBaseElement: {
        prototype: HTMLAmortizationScheduleBaseElement;
        new (): HTMLAmortizationScheduleBaseElement;
    };
    interface HTMLAmortizationScheduleWithAdditionalElement extends Components.AmortizationScheduleWithAdditional, HTMLStencilElement {
    }
    var HTMLAmortizationScheduleWithAdditionalElement: {
        prototype: HTMLAmortizationScheduleWithAdditionalElement;
        new (): HTMLAmortizationScheduleWithAdditionalElement;
    };
    interface HTMLAmortizationScheduleWithoutAdditionalElement extends Components.AmortizationScheduleWithoutAdditional, HTMLStencilElement {
    }
    var HTMLAmortizationScheduleWithoutAdditionalElement: {
        prototype: HTMLAmortizationScheduleWithoutAdditionalElement;
        new (): HTMLAmortizationScheduleWithoutAdditionalElement;
    };
    interface HTMLBalanceGraphElement extends Components.BalanceGraph, HTMLStencilElement {
    }
    var HTMLBalanceGraphElement: {
        prototype: HTMLBalanceGraphElement;
        new (): HTMLBalanceGraphElement;
    };
    interface HTMLBarChartElementEventMap {
        "rowClicked": AmortizationRow;
    }
    interface HTMLBarChartElement extends Components.BarChart, HTMLStencilElement {
        addEventListener<K extends keyof HTMLBarChartElementEventMap>(type: K, listener: (this: HTMLBarChartElement, ev: BarChartCustomEvent<HTMLBarChartElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLBarChartElementEventMap>(type: K, listener: (this: HTMLBarChartElement, ev: BarChartCustomEvent<HTMLBarChartElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLBarChartElement: {
        prototype: HTMLBarChartElement;
        new (): HTMLBarChartElement;
    };
    interface HTMLCumulativePaymentGraphElement extends Components.CumulativePaymentGraph, HTMLStencilElement {
    }
    var HTMLCumulativePaymentGraphElement: {
        prototype: HTMLCumulativePaymentGraphElement;
        new (): HTMLCumulativePaymentGraphElement;
    };
    interface HTMLDateInputElementEventMap {
        "dateChange": string;
    }
    interface HTMLDateInputElement extends Components.DateInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDateInputElementEventMap>(type: K, listener: (this: HTMLDateInputElement, ev: DateInputCustomEvent<HTMLDateInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDateInputElementEventMap>(type: K, listener: (this: HTMLDateInputElement, ev: DateInputCustomEvent<HTMLDateInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDateInputElement: {
        prototype: HTMLDateInputElement;
        new (): HTMLDateInputElement;
    };
    interface HTMLExportJsonControllerElement extends Components.ExportJsonController, HTMLStencilElement {
    }
    var HTMLExportJsonControllerElement: {
        prototype: HTMLExportJsonControllerElement;
        new (): HTMLExportJsonControllerElement;
    };
    interface HTMLKeyMetricsDashboardElement extends Components.KeyMetricsDashboard, HTMLStencilElement {
    }
    var HTMLKeyMetricsDashboardElement: {
        prototype: HTMLKeyMetricsDashboardElement;
        new (): HTMLKeyMetricsDashboardElement;
    };
    interface HTMLLoanAmortizationCalculatorElement extends Components.LoanAmortizationCalculator, HTMLStencilElement {
    }
    var HTMLLoanAmortizationCalculatorElement: {
        prototype: HTMLLoanAmortizationCalculatorElement;
        new (): HTMLLoanAmortizationCalculatorElement;
    };
    interface HTMLLoanCalculatorElementEventMap {
        "formValidityChange": boolean;
        "formSubmit": LoanFormData;
    }
    interface HTMLLoanCalculatorElement extends Components.LoanCalculator, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLoanCalculatorElementEventMap>(type: K, listener: (this: HTMLLoanCalculatorElement, ev: LoanCalculatorCustomEvent<HTMLLoanCalculatorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLoanCalculatorElementEventMap>(type: K, listener: (this: HTMLLoanCalculatorElement, ev: LoanCalculatorCustomEvent<HTMLLoanCalculatorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLoanCalculatorElement: {
        prototype: HTMLLoanCalculatorElement;
        new (): HTMLLoanCalculatorElement;
    };
    interface HTMLLoanCalculatorAppElement extends Components.LoanCalculatorApp, HTMLStencilElement {
    }
    var HTMLLoanCalculatorAppElement: {
        prototype: HTMLLoanCalculatorAppElement;
        new (): HTMLLoanCalculatorAppElement;
    };
    interface HTMLLoanCalculatorMainElement extends Components.LoanCalculatorMain, HTMLStencilElement {
    }
    var HTMLLoanCalculatorMainElement: {
        prototype: HTMLLoanCalculatorMainElement;
        new (): HTMLLoanCalculatorMainElement;
    };
    interface HTMLLoanDetailsElement extends Components.LoanDetails, HTMLStencilElement {
    }
    var HTMLLoanDetailsElement: {
        prototype: HTMLLoanDetailsElement;
        new (): HTMLLoanDetailsElement;
    };
    interface HTMLLoanReportElement extends Components.LoanReport, HTMLStencilElement {
    }
    var HTMLLoanReportElement: {
        prototype: HTMLLoanReportElement;
        new (): HTMLLoanReportElement;
    };
    interface HTMLLoanSummaryElementEventMap {
        "deleteLoan": string;
        "summaryTabChange": { loanId: string; tabIndex: number };
    }
    interface HTMLLoanSummaryElement extends Components.LoanSummary, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLoanSummaryElementEventMap>(type: K, listener: (this: HTMLLoanSummaryElement, ev: LoanSummaryCustomEvent<HTMLLoanSummaryElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLoanSummaryElementEventMap>(type: K, listener: (this: HTMLLoanSummaryElement, ev: LoanSummaryCustomEvent<HTMLLoanSummaryElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLoanSummaryElement: {
        prototype: HTMLLoanSummaryElement;
        new (): HTMLLoanSummaryElement;
    };
    interface HTMLNumberInputElementEventMap {
        "valueChange": { value: number; propertyName: string };
    }
    interface HTMLNumberInputElement extends Components.NumberInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNumberInputElementEventMap>(type: K, listener: (this: HTMLNumberInputElement, ev: NumberInputCustomEvent<HTMLNumberInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNumberInputElementEventMap>(type: K, listener: (this: HTMLNumberInputElement, ev: NumberInputCustomEvent<HTMLNumberInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNumberInputElement: {
        prototype: HTMLNumberInputElement;
        new (): HTMLNumberInputElement;
    };
    interface HTMLPayoffProgressElement extends Components.PayoffProgress, HTMLStencilElement {
    }
    var HTMLPayoffProgressElement: {
        prototype: HTMLPayoffProgressElement;
        new (): HTMLPayoffProgressElement;
    };
    interface HTMLPieChartElement extends Components.PieChart, HTMLStencilElement {
    }
    var HTMLPieChartElement: {
        prototype: HTMLPieChartElement;
        new (): HTMLPieChartElement;
    };
    interface HTMLPopupModalElementEventMap {
        "closePopup": void;
    }
    interface HTMLPopupModalElement extends Components.PopupModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPopupModalElementEventMap>(type: K, listener: (this: HTMLPopupModalElement, ev: PopupModalCustomEvent<HTMLPopupModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPopupModalElementEventMap>(type: K, listener: (this: HTMLPopupModalElement, ev: PopupModalCustomEvent<HTMLPopupModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPopupModalElement: {
        prototype: HTMLPopupModalElement;
        new (): HTMLPopupModalElement;
    };
    interface HTMLSavingsComparisonGraphElement extends Components.SavingsComparisonGraph, HTMLStencilElement {
    }
    var HTMLSavingsComparisonGraphElement: {
        prototype: HTMLSavingsComparisonGraphElement;
        new (): HTMLSavingsComparisonGraphElement;
    };
    interface HTMLScheduleSummaryElement extends Components.ScheduleSummary, HTMLStencilElement {
    }
    var HTMLScheduleSummaryElement: {
        prototype: HTMLScheduleSummaryElement;
        new (): HTMLScheduleSummaryElement;
    };
    interface HTMLScheduleViewElementEventMap {
        "rowClicked": AmortizationRow;
    }
    interface HTMLScheduleViewElement extends Components.ScheduleView, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScheduleViewElementEventMap>(type: K, listener: (this: HTMLScheduleViewElement, ev: ScheduleViewCustomEvent<HTMLScheduleViewElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScheduleViewElementEventMap>(type: K, listener: (this: HTMLScheduleViewElement, ev: ScheduleViewCustomEvent<HTMLScheduleViewElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScheduleViewElement: {
        prototype: HTMLScheduleViewElement;
        new (): HTMLScheduleViewElement;
    };
    interface HTMLTabsControllerElementEventMap {
        "tabChange": number;
    }
    interface HTMLTabsControllerElement extends Components.TabsController, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTabsControllerElementEventMap>(type: K, listener: (this: HTMLTabsControllerElement, ev: TabsControllerCustomEvent<HTMLTabsControllerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTabsControllerElementEventMap>(type: K, listener: (this: HTMLTabsControllerElement, ev: TabsControllerCustomEvent<HTMLTabsControllerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTabsControllerElement: {
        prototype: HTMLTabsControllerElement;
        new (): HTMLTabsControllerElement;
    };
    interface HTMLTextInputElementEventMap {
        "valueChange": { value: string; propertyName: string };
    }
    interface HTMLTextInputElement extends Components.TextInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTextInputElementEventMap>(type: K, listener: (this: HTMLTextInputElement, ev: TextInputCustomEvent<HTMLTextInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTextInputElementEventMap>(type: K, listener: (this: HTMLTextInputElement, ev: TextInputCustomEvent<HTMLTextInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTextInputElement: {
        prototype: HTMLTextInputElement;
        new (): HTMLTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "amortization-entry": HTMLAmortizationEntryElement;
        "amortization-list": HTMLAmortizationListElement;
        "amortization-schedule": HTMLAmortizationScheduleElement;
        "amortization-schedule-base": HTMLAmortizationScheduleBaseElement;
        "amortization-schedule-with-additional": HTMLAmortizationScheduleWithAdditionalElement;
        "amortization-schedule-without-additional": HTMLAmortizationScheduleWithoutAdditionalElement;
        "balance-graph": HTMLBalanceGraphElement;
        "bar-chart": HTMLBarChartElement;
        "cumulative-payment-graph": HTMLCumulativePaymentGraphElement;
        "date-input": HTMLDateInputElement;
        "export-json-controller": HTMLExportJsonControllerElement;
        "key-metrics-dashboard": HTMLKeyMetricsDashboardElement;
        "loan-amortization-calculator": HTMLLoanAmortizationCalculatorElement;
        "loan-calculator": HTMLLoanCalculatorElement;
        "loan-calculator-app": HTMLLoanCalculatorAppElement;
        "loan-calculator-main": HTMLLoanCalculatorMainElement;
        "loan-details": HTMLLoanDetailsElement;
        "loan-report": HTMLLoanReportElement;
        "loan-summary": HTMLLoanSummaryElement;
        "number-input": HTMLNumberInputElement;
        "payoff-progress": HTMLPayoffProgressElement;
        "pie-chart": HTMLPieChartElement;
        "popup-modal": HTMLPopupModalElement;
        "savings-comparison-graph": HTMLSavingsComparisonGraphElement;
        "schedule-summary": HTMLScheduleSummaryElement;
        "schedule-view": HTMLScheduleViewElement;
        "tabs-controller": HTMLTabsControllerElement;
        "text-input": HTMLTextInputElement;
    }
}
declare namespace LocalJSX {
    interface AmortizationEntry {
        "onAddEntry"?: (event: AmortizationEntryCustomEvent<AmortizationData>) => void;
    }
    interface AmortizationList {
        /**
          * @default []
         */
        "entries"?: AmortizationData[];
        "onDeleteEntry"?: (event: AmortizationListCustomEvent<string>) => void;
    }
    interface AmortizationSchedule {
        /**
          * @default []
         */
        "schedule"?: AmortizationRow[];
    }
    interface AmortizationScheduleBase {
        /**
          * @default []
         */
        "amortizationEntries"?: AmortizationData[];
        "loanData"?: LoanFormData;
    }
    interface AmortizationScheduleWithAdditional {
        /**
          * @default []
         */
        "amortizationEntries"?: AmortizationData[];
        "loanData"?: LoanFormData;
    }
    interface AmortizationScheduleWithoutAdditional {
        "loanData"?: LoanFormData;
    }
    interface BalanceGraph {
        /**
          * @default []
         */
        "schedule"?: AmortizationRow[];
    }
    interface BarChart {
        "onRowClicked"?: (event: BarChartCustomEvent<AmortizationRow>) => void;
        /**
          * @default []
         */
        "schedule"?: AmortizationRow[];
    }
    interface CumulativePaymentGraph {
        /**
          * @default []
         */
        "schedule"?: AmortizationRow[];
    }
    interface DateInput {
        /**
          * @default 'date-input'
         */
        "inputId"?: string;
        /**
          * @default ''
         */
        "max"?: string;
        "onDateChange"?: (event: DateInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface ExportJsonController {
    }
    interface KeyMetricsDashboard {
        "loanData"?: LoanFormData;
        /**
          * @default []
         */
        "schedule"?: AmortizationRow[];
    }
    interface LoanAmortizationCalculator {
    }
    interface LoanCalculator {
        /**
          * @default false
         */
        "hideAdditionalPrincipal"?: boolean;
        "initialFormData"?: LoanFormData;
        "onFormSubmit"?: (event: LoanCalculatorCustomEvent<LoanFormData>) => void;
        "onFormValidityChange"?: (event: LoanCalculatorCustomEvent<boolean>) => void;
    }
    interface LoanCalculatorApp {
    }
    interface LoanCalculatorMain {
    }
    interface LoanDetails {
        "loanData"?: LoanFormData;
    }
    interface LoanReport {
        "loanDataDictionary"?: { [key: string]: LoanFormData };
    }
    interface LoanSummary {
        "loanData"?: LoanFormData;
        "onDeleteLoan"?: (event: LoanSummaryCustomEvent<string>) => void;
        "onSummaryTabChange"?: (event: LoanSummaryCustomEvent<{ loanId: string; tabIndex: number }>) => void;
    }
    interface NumberInput {
        /**
          * @default null
         */
        "max"?: number;
        /**
          * @default 0
         */
        "min"?: number;
        /**
          * @default 2
         */
        "numberOfDecimalsAllowed"?: number;
        /**
          * @default NumericInputTypeEnum.Integer
         */
        "numericInputType"?: NumericInputTypeEnum;
        "onValueChange"?: (event: NumberInputCustomEvent<{ value: number; propertyName: string }>) => void;
        /**
          * @default ''
         */
        "propertyName"?: string;
        /**
          * @default true
         */
        "required"?: boolean;
        /**
          * @default null
         */
        "value"?: number;
    }
    interface PayoffProgress {
        /**
          * @default []
         */
        "amortizationEntries"?: AmortizationData[];
        "currentDate"?: string;
        "loanData"?: LoanFormData;
    }
    interface PieChart {
        /**
          * @default []
         */
        "schedule"?: AmortizationRow[];
    }
    interface PopupModal {
        /**
          * @default false
         */
        "isOpen"?: boolean;
        "modalTitle"?: string;
        "onClosePopup"?: (event: PopupModalCustomEvent<void>) => void;
    }
    interface SavingsComparisonGraph {
        /**
          * @default []
         */
        "amortizationEntries"?: AmortizationData[];
        "loanData"?: LoanFormData;
    }
    interface ScheduleSummary {
        /**
          * @default []
         */
        "schedule"?: AmortizationRow[];
    }
    interface ScheduleView {
        "onRowClicked"?: (event: ScheduleViewCustomEvent<AmortizationRow>) => void;
        /**
          * @default []
         */
        "schedule"?: AmortizationRow[];
    }
    interface TabsController {
        /**
          * @default 0
         */
        "defaultActiveIndex"?: number;
        "onTabChange"?: (event: TabsControllerCustomEvent<number>) => void;
        /**
          * @default []
         */
        "tabs"?: TabItem[];
    }
    interface TextInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default null
         */
        "maxLength"?: number;
        "onValueChange"?: (event: TextInputCustomEvent<{ value: string; propertyName: string }>) => void;
        /**
          * @default ''
         */
        "propertyName"?: string;
        /**
          * @default true
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "amortization-entry": AmortizationEntry;
        "amortization-list": AmortizationList;
        "amortization-schedule": AmortizationSchedule;
        "amortization-schedule-base": AmortizationScheduleBase;
        "amortization-schedule-with-additional": AmortizationScheduleWithAdditional;
        "amortization-schedule-without-additional": AmortizationScheduleWithoutAdditional;
        "balance-graph": BalanceGraph;
        "bar-chart": BarChart;
        "cumulative-payment-graph": CumulativePaymentGraph;
        "date-input": DateInput;
        "export-json-controller": ExportJsonController;
        "key-metrics-dashboard": KeyMetricsDashboard;
        "loan-amortization-calculator": LoanAmortizationCalculator;
        "loan-calculator": LoanCalculator;
        "loan-calculator-app": LoanCalculatorApp;
        "loan-calculator-main": LoanCalculatorMain;
        "loan-details": LoanDetails;
        "loan-report": LoanReport;
        "loan-summary": LoanSummary;
        "number-input": NumberInput;
        "payoff-progress": PayoffProgress;
        "pie-chart": PieChart;
        "popup-modal": PopupModal;
        "savings-comparison-graph": SavingsComparisonGraph;
        "schedule-summary": ScheduleSummary;
        "schedule-view": ScheduleView;
        "tabs-controller": TabsController;
        "text-input": TextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "amortization-entry": LocalJSX.AmortizationEntry & JSXBase.HTMLAttributes<HTMLAmortizationEntryElement>;
            "amortization-list": LocalJSX.AmortizationList & JSXBase.HTMLAttributes<HTMLAmortizationListElement>;
            "amortization-schedule": LocalJSX.AmortizationSchedule & JSXBase.HTMLAttributes<HTMLAmortizationScheduleElement>;
            "amortization-schedule-base": LocalJSX.AmortizationScheduleBase & JSXBase.HTMLAttributes<HTMLAmortizationScheduleBaseElement>;
            "amortization-schedule-with-additional": LocalJSX.AmortizationScheduleWithAdditional & JSXBase.HTMLAttributes<HTMLAmortizationScheduleWithAdditionalElement>;
            "amortization-schedule-without-additional": LocalJSX.AmortizationScheduleWithoutAdditional & JSXBase.HTMLAttributes<HTMLAmortizationScheduleWithoutAdditionalElement>;
            "balance-graph": LocalJSX.BalanceGraph & JSXBase.HTMLAttributes<HTMLBalanceGraphElement>;
            "bar-chart": LocalJSX.BarChart & JSXBase.HTMLAttributes<HTMLBarChartElement>;
            "cumulative-payment-graph": LocalJSX.CumulativePaymentGraph & JSXBase.HTMLAttributes<HTMLCumulativePaymentGraphElement>;
            "date-input": LocalJSX.DateInput & JSXBase.HTMLAttributes<HTMLDateInputElement>;
            "export-json-controller": LocalJSX.ExportJsonController & JSXBase.HTMLAttributes<HTMLExportJsonControllerElement>;
            "key-metrics-dashboard": LocalJSX.KeyMetricsDashboard & JSXBase.HTMLAttributes<HTMLKeyMetricsDashboardElement>;
            "loan-amortization-calculator": LocalJSX.LoanAmortizationCalculator & JSXBase.HTMLAttributes<HTMLLoanAmortizationCalculatorElement>;
            "loan-calculator": LocalJSX.LoanCalculator & JSXBase.HTMLAttributes<HTMLLoanCalculatorElement>;
            "loan-calculator-app": LocalJSX.LoanCalculatorApp & JSXBase.HTMLAttributes<HTMLLoanCalculatorAppElement>;
            "loan-calculator-main": LocalJSX.LoanCalculatorMain & JSXBase.HTMLAttributes<HTMLLoanCalculatorMainElement>;
            "loan-details": LocalJSX.LoanDetails & JSXBase.HTMLAttributes<HTMLLoanDetailsElement>;
            "loan-report": LocalJSX.LoanReport & JSXBase.HTMLAttributes<HTMLLoanReportElement>;
            "loan-summary": LocalJSX.LoanSummary & JSXBase.HTMLAttributes<HTMLLoanSummaryElement>;
            "number-input": LocalJSX.NumberInput & JSXBase.HTMLAttributes<HTMLNumberInputElement>;
            "payoff-progress": LocalJSX.PayoffProgress & JSXBase.HTMLAttributes<HTMLPayoffProgressElement>;
            "pie-chart": LocalJSX.PieChart & JSXBase.HTMLAttributes<HTMLPieChartElement>;
            "popup-modal": LocalJSX.PopupModal & JSXBase.HTMLAttributes<HTMLPopupModalElement>;
            "savings-comparison-graph": LocalJSX.SavingsComparisonGraph & JSXBase.HTMLAttributes<HTMLSavingsComparisonGraphElement>;
            "schedule-summary": LocalJSX.ScheduleSummary & JSXBase.HTMLAttributes<HTMLScheduleSummaryElement>;
            "schedule-view": LocalJSX.ScheduleView & JSXBase.HTMLAttributes<HTMLScheduleViewElement>;
            "tabs-controller": LocalJSX.TabsController & JSXBase.HTMLAttributes<HTMLTabsControllerElement>;
            "text-input": LocalJSX.TextInput & JSXBase.HTMLAttributes<HTMLTextInputElement>;
        }
    }
}
